ADD support for injecting headerFields into Request
netceteragroup/GirdersSwift pull request #30
Opened 2023-10-30 09:29 UTC by mihailnacev

2023-10-30 09:52 UTC, composers requested changes

2023-10-30 09:52 UTC, composers commented on Sources/GirdersSwift/http/Request.swift
> +                headerFields: [String: String] = [:],
I would call this additionalHeaderFields.

2023-10-30 09:52 UTC, composers commented on Tests/GirdersSwiftTests/swift/http/TestRequest.swift
> +    func testRequestWithHeaderFields() {
Write another test without additionalHeaderFields to test that nothing will be added.

2023-10-31 08:03 UTC, composers submitted a review, later dismissed

2023-10-31 09:33 UTC, composers approved these changes

2023-10-31 09:53 UTC, km-tp approved these changes

2023-10-31 09:56 UTC, marijamicevska approved these changes

2023-10-31 10:02 UTC, merged